### PR TITLE
defer reactor import

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Review by wulczer — APPROVED** [review]
Looks good, thanks!

**Comment by wulczer** [comment]
@graingert already there ;) https://pypi.org/project/txpostgres/1.7.0/

**Comment by graingert** [comment]
@wulczer any chance of a wheel too?

**Comment by graingert** [comment]
Ah you need setuptools for a wheel

**Comment by wulczer** [comment]
Yeah, I've only been doing PyPI for this, hope you can build a wheel from the source package yourself...

**Pull request merged**
